# Generated by Django 2.1.7 on 2020-08-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensorName', models.CharField(max_length=30)),
                ('value1', models.CharField(max_length=30)),
                ('value2', models.CharField(max_length=30)),
                ('value3', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
