# Generated by Django 2.1.7 on 2020-08-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sensors',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
