# Generated by Django 2.1.7 on 2020-08-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200818_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodemcu_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val1', models.CharField(max_length=30)),
                ('val2', models.CharField(max_length=30)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
